### ISSUE TITLE
Error during rosdep install .....

### ISSUE THREAD

**Issue by stefanobinotto** [pal-robotics/tiago_moveit_config#13]
I launched the following command:
"rosdep install --from-paths src --ignore-src -y --rosdistro melodic --skip-keys="opencv2 opencv2-nonfree pal_laser_filters speed_limit_node sensor_to_cloud hokuyo_node libdw-dev python-graphitesend-pip python-statsd pal_filters pal_vo_server pal_usb_utils pal_pcl pal_pcl_points_throttle_and_filter pal_karto pal_local_joint_control camera_calibration_files pal_startup_msgs pal-orbbec-openni2 dummy_actuators_manager pal_local_planner gravity_compensation_controller current_limit_controller dynamic_footprint dynamixel_cpp tf_lookup opencv3 joint_impedance_trajectory_controller cartesian_impedance_controller omni_base_description omni_drive_controller"

and everything works except for this error:
**ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
tiago_moveit_config: Cannot locate rosdep definition for [pal_moveit_plugins]**

I notice that tiago_moveit_config has been updated a couple of days ago. How can i solve this error???
A friend of mine was able to complete the procedure without errors before the update made 2 days ago.

**Comment by saikishor** [comment]
Hello @stefanobinotto,

Regarding your issue, you need to use the updated `rosdep install`  in the page : http://wiki.ros.org/Robots/TIAGo/Tutorials/Installation/InstallUbuntuAndROS or just run the following command:

`    rosdep install --from-paths src --ignore-src -y --rosdistro melodic --skip-keys="opencv2 opencv2-nonfree pal_laser_filters speed_limit_node sensor_to_cloud hokuyo_node libdw-dev python-graphitesend-pip python-statsd pal_filters pal_vo_server pal_usb_utils pal_pcl pal_pcl_points_throttle_and_filter pal_karto pal_local_joint_control camera_calibration_files pal_startup_msgs pal-orbbec-openni2 dummy_actuators_manager pal_local_planner gravity_compensation_controller current_limit_controller dynamic_footprint dynamixel_cpp tf_lookup opencv3 joint_impedance_trajectory_controller cartesian_impedance_controller omni_base_description omni_drive_controller pal_moveit_capabilities pal_moveit_plugins"`

We hope this helps to fix your issue. Thank you,

Best Regards,
PAL Robotics Team.

**Comment by stefanobinotto** [comment]
Thank you very much
