### ISSUE TITLE
Differential-Drive Mobile Base and an Arm Planning ROS2 Humble 

### ISSUE THREAD

**Issue by kavikode** [pal-robotics/tiago_moveit_config#15]
Our goal is to follow the tutorial of Differential-Drive Mobile Base and an Arm Planning, link: https://moveit.picknik.ai/humble/doc/examples/mobile_base_arm/mobile_base_arm_tutorial.html

How do we setup the kinematics plugin to have a joint model group that consist of two joint model groups: one for the manipulator and the other one for the mobile base which has only one joint with planar type in the.srdf file in ROS2 Humble?

I am trying to edit the existing Moveit Configuration Package with the command:
 
ros2 launch moveit_setup_assistant setup_assistant.launch.py  

Using the contents of tiago.srdf.xacro, I created the file tiago.srdf with the parameters base_type:=pmb2 arm_type:=tiago-arm ft_sensor:=schunk-ft end_effector:=pal-gripper:

<?xml version="1.0" ?>

<robot name="tiago">

    
    
    
    
    

    
    <group name="arm">
        <joint name="arm_1_joint" />
        <joint name="arm_2_joint" />
        <joint name="arm_3_joint" />
        <joint name="arm_4_joint" />
        <joint name="arm_5_joint" />
        <joint name="arm_6_joint" />
        <joint name="arm_7_joint" />
        <joint name="arm_tool_joint" />
    </group>

    
    <group name="arm_torso">
        <joint name="torso_lift_joint" />
        <joint name="arm_1_joint" />
        <joint name="arm_2_joint" />
        <joint name="arm_3_joint" />
        <joint name="arm_4_joint" />
        <joint name="arm_5_joint" />
        <joint name="arm_6_joint" />
        <joint name="arm_7_joint" />
        <joint name="arm_tool_joint" />
    </group>

    
    <group name="gripper">
        <link name="gripper_left_finger_link" />
        <link name="gripper_right_finger_link" />
        <link name="gripper_link" />
        <joint name="gripper_left_finger_joint" />
        <joint name="gripper_right_finger_joint" />
    </group>

    
    <end_effector name="gripper" parent_link="arm_tool_link" group="gripper" parent_group="arm_torso" />

    
    
    
    <disable_collisions link1="base_link" link2="gripper_link" reason="default" />
    <disable_collisions link1="arm_tool_link" link2="gripper_left_finger_link" reason="default" />
    <disable_collisions link1="arm_tool_link" link2="gripper_right_finger_link" reason="default" />
    <disable_collisions link1="torso_lift_link" link2="gripper_link" reason="default" />

</robot>

Thank you

**Comment by saikishor** [comment]
@kavikode I believe this ticket should go to MoveIt as you are having problems reproducing their tutorials. 

I hope this helps. 

Best regards,
Sai

**Comment by kavikode** [comment]
thank you. Actually, the question is how to add motion planning for the mobile base of Tiago with the arm.

**Comment by saikishor** [comment]
> thank you. Actually, the question is how to add motion planning for the mobile base of Tiago with the arm.

What we do internally is using Nav2 navigation. We are not expertise in using MoveIt for doing the same.

**Comment by kavikode** [comment]
An particular for the Stretch robot, they had created a stretch_kinematics_plugin/StretchKinematicsPlugin as a kinematics solver with the source code at `[](https://github.com/PickNikRobotics/stretch_moveit_plugins/blob/main/stretch_kinematics_plugin/src/stretch_kinematics_plugin.cpp)`.

Likewise, I had thought there could be something similar for Tiago.

I wonder if the same code could work. Any suggestions, please?

Thank you

**Comment by saikishor** [comment]
Hello @kavikode!

I don't think we have something similar to this. You can give it a try to see if it works. This is something that we cannot help you as I said earlier, we use Nav2 but not with this approach. 

Best Regards,
PAL Robotics Team
