### ISSUE TITLE
kinetic-devel: srdf broken

### ISSUE THREAD

**Issue by LeroyR** [pal-robotics/tiago_moveit_config#7]
atleast _pal_gripper.srdf is malformed. 
Planning is not possible as it is in self collision state:

[ INFO] [1548853581.007192186, 268.780000000]: Found a contact between 'arm_6_link' (type 'Robot link') and 'arm_5_link' (type 'Robot link'), which constitutes a collision. Contact information is not stored.

The srdf disables this collision but it is somehow not registered in moveit (no error messages either)

Works by using the "old" srdf https://github.com/CentralLabFacilities/tiago_ros_pkgs/commit/6d2971347900a0dd658346d6a453b30cdf21910c#diff-8cdc534e85652d58aa94264ed3487efe

**Comment by v-lopez** [comment]
Hi @LeroyR,

Could you give us some steps to reproduce it?

We just started from scratch on a new computer, followed all the steps to install and run on the tutorial, launched the simulation and where able to perform moveit plans without collisions.

We tried with Hey5 + FT and with Gripper and NoFT.

Is the initial movement done?

![image](https://user-images.githubusercontent.com/3469405/52053999-5502a880-255b-11e9-8f2c-631a920dcd79.png)

![image](https://user-images.githubusercontent.com/3469405/52054052-867b7400-255b-11e9-8c4d-c085377e45fd.png)

**Comment by LeroyR** [comment]
I did not try the basic installation - so it could actually be a problem with some custom pkgs. nonetheless:

1. we updated all launch files/configs form steel/iron/etc to gripper/no_gripper etc
2. sim startup process -> arm is not tucked -> moveit logs show collision in adjacent links
3. changed the comment in the first line of pal_gripper.srdf to something else, launched move_group and confirmed the file is loaded with rosparam get -> collision in adjacent links
4. replace the content of the srdf with the old version and restarted -> arm is tucking

so we **assumed** the multiline comment in the srdf is the culprit as i know some tools are not handling xml comments well

I get back to you if i find time to investigate/reproduce the error.

**Comment by v-lopez** [comment]
Hi @LeroyR, I see that you are one of our customers and have a real TIAGo.

You should not mix our public packages with the real robot, you should use the ISO that was provided to you.

They are not updated at the same time and can be incompatible.

**Comment by LeroyR** [comment]
This is for simulation env for Students. We use no pal-private pkgs for this.
